### ISSUE TITLE
更新数据失败

### ISSUE THREAD

**Issue by yanzhensong** [vnpy/vnpy_datamanager#10]
9e4500d 这个 commit 更改了 ManagerEngine 的 download_bar_data 的接口，导致更新数据时失败。
![image](https://user-images.githubusercontent.com/11738982/224470536-5c07e9aa-bfdb-4457-96c3-23b76edc6cc0.png)

**Comment by vnpy** [comment]
`pip install vnpy_datamanger --upgrade`

升级到最新版即可

**Comment by yanzhensong** [comment]
我用的就是最新版，1.0.8版本的，你看下 widget.py 384 行，这个 download_bar_data 没有传入 output 参数
@vnpy

**Comment by vnpy** [comment]
不好意思，已经修复，非常感谢反馈
